### ISSUE TITLE
Twig extensions conflicts with apps implementing it

### ISSUE THREAD

**Issue by gorkalaucirica** [LIN3S/PatternLibraryBuilder#16]
As we have some generic twig extension names such as 'icon' and 'find_icons' we can have some issues when pattern library is integrated in other applications.

Add a namespace (`lin3s_pattern_library_***` for example) and replace occurrences of these function names

**Comment by mktoast** [comment]
This has been resolved in the next PR
https://github.com/LIN3S/PatternLibraryBuilder/pull/24

**Comment by gorkalaucirica** [comment]
Closed by #24
